name: Notify Discord on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    name: Notify Team
    steps:
    - name: Linux Test Info
      uses: rjstone/discord-webhook-notify@v1
      with:
        severity: info
        username: Github Issue Bot
        color: '#ff00aa'
        avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
        description: ${{ github.event.issue.title }}
        details: ${{ github.event.issue.body }}
        footer: Kubix App
        text: New Issue created. URL (${{ github.event.issue.html_url }})
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
    